### ISSUE TITLE
HTML returned during when auth is invalid

### ISSUE THREAD

**Issue by pfista** [nylas/nylas-ruby#109]
Reported by a customer:

We are using your gem to exchange the code for an access token
(which is a simple HTTP call that returns JSON)
but you don’t return JSON if the code is invalid. Are we missing something?

So to fix this using your gem we need to rescue JSON parser errors and look at the HTML response, which is not ideal.

If I do the request, we were hoping you give back an http status code that is indicative of this particular failure or else we are grepping for `/the code you provided is not valid/`

And this is not a good way to handle errors. Can you get this fixed or let me know what we are doing wrong.

![image](https://user-images.githubusercontent.com/728526/32301376-f74f028a-bf1a-11e7-9c82-6de999ad5901.png)

**Comment by zspencer** [comment]
@pfista / @khamidou - This could be because the SDK doesn't send the content_type as part of the code exchange.  I'm going to mark this as a bug and put it in the to prioritize milestone.

**Comment by arunagw** [comment]
I have verified this and this has been fixed in latest version details. More details can be found here https://github.com/nylas/nylas-ruby/issues/278#issuecomment-816815247
