### ISSUE TITLE
Support Nylas Native Authentication API Directly

### ISSUE THREAD

**Issue by zspencer** [nylas/nylas-ruby#114]
Nylas Native Authentication provides the ability to generate a nylas token from user credentials. This allows clients to write their own user interface, however it also has users entering credentials directly into a UI that isn't owned by the service provider.

We want to encapsulate this within the Nylas SDK.

**Comment by arunagw** [comment]
Closing this as this was implemented in https://github.com/nylas/nylas-ruby/pull/178
