### ISSUE TITLE
Support `id` views for collections

### ISSUE THREAD

**Issue by zspencer** [nylas/nylas-ruby#117]
Currently, RestfulCollection doesn't support all the views we'd want. In particular [the `ids`view is pretty useful](https://docs.nylas.com/reference#views)

**Comment by arunagw** [comment]
This seems to be already supported. Confirmed working with v4.6.6

Example:

```
nylas = Nylas::API.new(app_id: 'app-id', app_secret: 'app-secret', access_token: 'token')
nylas.messages.ids
nylas.threads.ids
..
```
