### ISSUE TITLE
Add support for "Busy" and "notify participants" flag in events

### ISSUE THREAD

**Issue by zspencer** [nylas/nylas-ruby#124]
Event's also have a `busy` attribute: https://docs.nylas.com/reference#get-events. Let's get that working as well.

**Comment by arunagw** [comment]
Seems like we already have this here https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/event.rb#L20 and https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/event.rb#L40
