### ISSUE TITLE
Convert our compatibility matrix to one of the existing standards

### ISSUE THREAD

**Issue by zspencer** [nylas/nylas-ruby#146]
While I was able to throw together a cross-compatible test suite, it depends on using rbenv and doesn't really work for non-OS X users.

It would be great if some lovely soul took the time to convert our `bin/test` and `bin/build` script to something like [gemika](https://github.com/makandra/gemika) or [appraisal](https://github.com/thoughtbot/appraisal)

**Comment by arunagw** [comment]
We are running GitHub actions now which runs specs for all supported ruby version. I guess we can close this for now and revisit this in future if required.
