### ISSUE TITLE
Include CodeClimate and OverCommit so that we can give contributors fast feedback

### ISSUE THREAD

**Issue by zspencer** [nylas/nylas-ruby#148]
In order to ensure we're working towards a clean code base together with objective measures, it would be great to have code climate and overcommit set up.

Ideally overcommit will:

* Use Rubocop to lint the changes without linting unchanged files before committing
* Run the entire test suite before pushing

And CodeClimate will:
* Provide test coverage reporting so we can identify risk areas easier
* Give us a :+1: or :-1: on changes if they decrease compliance with the repositories standards.

**Comment by adarsh** [comment]
Also RuboCop?

**Comment by zspencer** [comment]
Good catch! Added that to the issue.
