### ISSUE TITLE
Delta sync path missing slash

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#18]
``path`` (https://github.com/inboxapp/inbox-ruby/blob/56903ba800ffccd8d486b4b7e023dec5208065b9/lib/namespace.rb#L64) being generated: 
"https://omitted:@api.nilas.**comn**/omitted/delta/generate_cursor"

    SocketError: getaddrinfo: Name or service not known
      from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
      from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `open'
      from /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
      from /usr/local/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
      from /usr/local/lib/ruby/2.2.0/net/http.rb:878:in `connect'
      from /usr/local/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
      from /usr/local/lib/ruby/2.2.0/net/http.rb:852:in `start'
      from /usr/local/bundle/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
      from /usr/local/bundle/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
      from /usr/local/bundle/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
      from /usr/local/bundle/gems/rest-client-1.7.3/lib/restclient.rb:69:in `post'
      from /usr/local/bundle/bundler/gems/inbox-ruby-941084312c05/lib/namespace.rb:69:in `get_cursor'
      from /usr/src/app/app/models/inboxapp_user.rb:22:in `cursor'

All other requests work fine.

inbox-ruby version: https://github.com/inboxapp/inbox-ruby/tree/56903ba800ffccd8d486b4b7e023dec5208065b9

**Comment by khamidou** [comment]
I'm looking into this. I'll keep you updated.

**Comment by ajhodges** [comment]
Looks like this is fixed in PR #17 .. needs merging
