### ISSUE TITLE
Please add more information for redirecting the user to Nylas in Upgrade doc.

### ISSUE THREAD

**Issue by mechanicles** [nylas/nylas-ruby#182]
Currently, the upgrade guide, https://github.com/nylas/nylas-ruby/wiki/Upgrading-from-3.X-to-4.0 has limited information. Now, there is no information about redirecting the user to Nylas. It would be good if you guys add those so we can try Nylas 4 version.

**Update: These following steps**

**Step 1: Redirect the user to Nylas:**

```ruby
require 'nylas'

def login
  nylas = Nylas::API.new(config.nylas_app_id, config.nylas_app_secret, nil)
  # The email address of the user you want to authenticate
  user_email = 'ben@nylas.com'

  # This URL must be registered with your application in the developer portal
  callback_url = url_for(:action => 'login_callback')

  # You can also optionally pass state, an optional arbitrary string that
  # will be passed back to us at the end of the auth flow.
  redirect_to nylas.url_for_authentication(callback_url, user_email, {:state => 'ben auth'})
end
```

**Step 2: Handle the Authentication Response:**

```ruby
def login_callback
  nylas = Nylas::API.new(config.nylas_app_id, config.nylas_app_secret, nil)
  nylas_token = nylas.token_for_code(params[:code])

  # Save the nylas_token to the current session, save it to the user model, etc.
end
```

**Comment by arunagw** [comment]
Hey @mechanicles thanks for reporting this. After seeing this issue after a long time I am not sure if you are still looking for some upgrade docs but if you are please let me know and will try to add some docs to upgrade documentation.

**Comment by mechanicles** [comment]
@arunagw I am going to close this as I am no longer working for that project where we were using this gem. Documentation might have got updated but not sure.
