### ISSUE TITLE
Can't seem to set labels on a message

### ISSUE THREAD

**Issue by dv** [nylas/nylas-ruby#183]
What's the best practice to update labels on a message? I can't seem to get it to work.

Trying to save a message:
```ruby
[75] pry(main)> message.save
Nylas::InvalidRequest: Invalid id: {u'display_name': u'All Mail', u'id': u'43jzq92uc9gqd8wreu4bw71ws', u'name': u'all'}
from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nylas-4.2.0/lib/nylas/http_client.rb:141:in `handle_anticipated_failure_mode'
```

Trying to update the labels (`trash(api)` returns the `Nylas::Label` trash label):
```ruby
[76] pry(main)> message.update(labels: [trash(api)])
Nylas::InvalidRequest: Invalid id: {u'object': u'label', u'display_name': u'Trash', u'id': u'21hi7mcls49kn1yssqnw54vh4', u'account_id': xxxx'}
from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nylas-4.2.0/lib/nylas/http_client.rb:141:in `handle_anticipated_failure_mode'
```

Just sending the IDs doesn't work either:
```ruby
[77] pry(main)> message.update(labels: [trash(api).id])
TypeError: labels Unable to cast 21hi7mcls49kn1yssqnw54vh4 to a Nylas::Label
from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nylas-4.2.0/lib/nylas/model/attributes.rb:23:in `rescue in cast'
```

Considering that not changing anything and just calling `save` on a message already fails with an error, I'm leaning towards there being a bug in the ruby lib.

**Comment by BenLloydPearson** [comment]
Hi @dv, #231 adds the ability to set labels on messages, you can now do this like so: `message.update(label_ids: ['label-1-id', 'label-2-id'])`

To your second point about having issues with .save, we have also noticed some inconsistencies with this function and we are currently looking into fixing it. I will let you know when we've fixed this.

**Comment by BenLloydPearson** [comment]
Release 4.6.0 should fix the issues you're experiencing with .save. Please update to the latest version and let us know if you have any more issues with this.
