### ISSUE TITLE
Could not find ability to use Message Tracking

### ISSUE THREAD

**Issue by andy-vin** [nylas/nylas-ruby#184]
I'm trying to upgrade your gem from 3.0.0 version to 4.2.0 and couldn't find the ability to use mail tracking.
Could you provide an example in `nylas-ruby/examples/plain-ruby/` or maybe you forgot to add it after/before `headers` like here -> `https://github.com/nylas/nylas-ruby/blob/a12cd268fe501e98b9a16445e84b450cd756a2fd/lib/nylas/message.rb#L15`
Thanks a lot for your answer

**Comment by arunagw** [comment]
@andy-vin thanks for pointing it out. We are in progress to update our documentation and once it's updated it will have how `headers` can be fetched. But here is an example how you can fetch headers for a message and then use attributes from it.

```
message = nylas.messages.find('message-id')
message = message.expanded 
headers = message.headers
puts headers.in_reply_to
puts headers.message_id
puts headers.references
```

**Comment by arunagw** [comment]
Closing this for now. Please feel free to reopen this if it's still and issue. Thanks.
