### ISSUE TITLE
Fix encoding when try to download file from message

### ISSUE THREAD

**Issue by andy-vin** [nylas/nylas-ruby#185]
When I try to download a file from the message I got an error:
`Encoding::UndefinedConversionError: "\x84" from ASCII-8BIT to UTF-8`
The solution for this - change line into file
`https://github.com/nylas/nylas-ruby/blob/a12cd268fe501e98b9a16445e84b450cd756a2fd/lib/nylas/file.rb#L52`
from `temp_file = Tempfile.new(filename)`
to `temp_file = Tempfile.new(filename, encoding: 'ascii-8bit')`

**Comment by BenLloydPearson** [comment]
Closed via #193
