### ISSUE TITLE
"api is not defined as an attribute on" warnings on enumeration

### ISSUE THREAD

**Issue by timdorr** [nylas/nylas-ruby#188]
I'm seeing errors like this when using the `.each` iterator on any `Collection` object:

```
W, [2018-07-27T13:56:02.919881 #31343]  WARN -- : api is not defined as an attribute on Nylas::Message
```
And just to confirm that I'm not totally crazy, it looks like you are too: https://travis-ci.org/nylas/nylas-ruby/jobs/406871743

The source of the issue is merging in the `api` instance to the model initialize method: 

https://github.com/nylas/nylas-ruby/blob/b8623d4721abce785451372ff69b52e78533c88e/lib/nylas/collection.rb#L65

During the model initialize method in the `Attributable` decorator, it checks for that field as an attribute definition:

https://github.com/nylas/nylas-ruby/blob/b8623d4721abce785451372ff69b52e78533c88e/lib/nylas/model/attributable.rb#L9-L17

While that's an `attr_accessor` on `Model`, it's not an `attribute` class definition and fails that check.

I'm not sure what the best course of action would be here (hence the issue instead of PR). You could whitelist that attribute, define it on the `Model` as a default for all models, or not merge it and pass it in some other way. I'm not sure what's best, but if you have some opinion about it, I can put together a PR.

**Comment by zspencer** [comment]
Good catch @timdorr! Maybe instead of checking `attribute_definitions.key?` we should be checking `respond_to?(:"#{key}=")`. I've got a PR open that I'm resolving today that I can add that into as well.

**Comment by HayleyCAnderson** [comment]
Thanks for this excellent bug report @timdorr! I merged the PR from @zspencer and released 4.2.3 which should fix the issue.

**Comment by timdorr** [comment]
@HayleyCAnderson It looks like 4.2.3 was published prior to that fix going in: https://rubygems.org/gems/nylas/versions

Looks like someone bumped the version without committing/pushing the change back to this repo. Not sure what you want to do, but it looks like a 4.2.4 release would be warranted.

**Comment by HayleyCAnderson** [comment]
Wow, thanks for catching that. Sorry about that; just put up 4.2.4 https://rubygems.org/gems/nylas/versions/4.2.4

**Comment by timdorr** [comment]
No worries. Thank you!
