### ISSUE TITLE
Example app: config.inbox_api_server

### ISSUE THREAD

**Issue by intelliot** [nylas/nylas-ruby#19]
What is this?

![screen_shot_2015-04-01_at_10_38_51_pm](https://cloud.githubusercontent.com/assets/81505/6958465/4ee8cda2-d8c1-11e4-8d44-8cc9e4ba7326.png)

```ruby
    if config.inbox_api_server
        @inbox = Inbox::API.new(config.inbox_app_id, config.inbox_app_secret, session[:inbox_token], config.inbox_api_server, config.inbox_auth_domain)
    else
        @inbox = Inbox::API.new(config.inbox_app_id, config.inbox_app_secret, session[:inbox_token])
    end
```

The app seems to mostly work if I just remove the requirement for `config.inbox_api_server`

**Comment by bengotow** [comment]
Hey Elliot—thanks for reporting this. I'll take a look. The `inbox_api_server` environment variable was meant to be an easy way to point the ruby gem at another host. It defaults to `https://api.nilas.com`, but you could use it to point to your own version of the open-source sync engine. I think you should be able to resolve this by putting it in your `environments/*.rb` files along with your `inbox_app_id` and secret.
