### ISSUE TITLE
How delete a single occurrence of an event?

### ISSUE THREAD

**Issue by pauldruziak** [nylas/nylas-ruby#191]
I tried to expand the recurring event to get an instance that I need to delete. Then change the status of this instance to canceled and call `save`. But it seems that you don't support this operation because I get next error: `Nylas::InvalidRequest: Invalid id: c3r9qtwevtwhu71grkvcck5f0_20181029T153000Z`. How I can delete/update single occurrence in another way?

**Comment by arunagw** [comment]
@pauldruziak we have a `.destroy` call available on event object to call delete api for the given event.

Please give it a try and see if it's working for your case. Closing this issue for now and feel free to open again if `.destroy` is not working for you. Thanks.


API Doc: https://docs.nylas.com/reference#eventsid-1

Example:
```
# Deleting an event
event = nylas.events.find(id)
event.destroy
```
