### ISSUE TITLE
Can't chain "where" and "limit" methods when querying for events

### ISSUE THREAD

**Issue by frederickdubois** [nylas/nylas-ruby#198]
If, for example, I want to retrieve the next 5 events in a user's account, I would have to be able to use both the "where" and "limit" method. Each method works fine when taken separately, but they can't be used together on a same collection, making the use case above impossible to achieve even if very simple...

```ruby
# example...
events = nylas.events.where(starts_after: Time.now.to_i, expand_recurring: true).limit(5)
```

**Comment by BenLloydPearson** [comment]
Hi @frederickdubois apologies for the late reply, but this bug has been fixed and the code example you provided should now work.
