### ISSUE TITLE
For events, the 'when' attributes works only for events in "timespan" mode

### ISSUE THREAD

**Issue by frederickdubois** [nylas/nylas-ruby#199]
The `when`  attribute will have different return formats from the API depending on the type of date/time used for the event... Only the "timespan" works currently via the nylas-ruby library...

Examples values for different possible `when` attributes:

```ruby
# when 'timespan', I'm ok!
{:object=>"timespan", :start_time=>1543456800, :end_time=>1543458600}

# when 'date', I don't have the date...
{:object=>"date", :start_time=>0, :end_time=>0}

# when 'datespan', I don't have any of the 2 dates...
{:object=>"datespan", :start_time=>0, :end_time=>0}
```

Testing directly with the API we can see the different return formats... 
https://docs.nylas.com/reference#get-events

**Comment by arunagw** [comment]
Closing this issue now as #215 solved it. @frederickdubois Please let us know if it's still an issue. Thanks
