### ISSUE TITLE
Support saving/serializing empty values

### ISSUE THREAD

**Issue by rylwin** [nylas/nylas-ruby#221]
Without being able to save empty values, it is not possible to "unset" fields using the nylas ruby gem. Perhaps I'm missing a method or note in the documentation about how to do this, but it appears to me that it is not possible to set a value to nil or an empty string/array/etc.

For example, say you create the following event:

```
event = api.events.create(title: "A fun event!", location: "The Party Zone")
```

And then you decide you don't want a location, so you try:

```
event.update(location: "")
```

The resulting HTTP request does not include the param `location`, as it is removed during [`Attributes#serialize`](https://github.com/nylas/nylas-ruby/blob/5453cf9b2e9d80ee55e38ff5a6c8b19b8d5c262d/lib/nylas/model/attributes.rb#L36) (really [`Attributes#to_h`](https://github.com/nylas/nylas-ruby/blob/5453cf9b2e9d80ee55e38ff5a6c8b19b8d5c262d/lib/nylas/model/attributes.rb#L32)). The result is that, when you open your calendar, the location is still there.

While this approach (of dropping empty values) makes sense when trying to update just some information without fully loading the event data (e.g., we wouldn't want `Event.new(id: "...", location: "some location").save` to blank out title, times, etc.), it means we cannot blank out fields such as `location`, `participants`, or any other optional fields. 

A few ideas on how saving empty values might be supported:

* When an event is loaded via an API call, we can assume we have all data for the event. When `#save` or `#update` is called, it can realize that we have all of the event data, and thus perform the `#serialize`/`#to_h` operations without dropping empty objects (perhaps by passing a flag).

* Allow the user to pass a flag to `#update/#save` that would perform `#serialize/#to_h` without dropping empties.

* Add a `#save/update_all_attributes` method that would perform `#serialize/#to_h` without dropping empties.

There are probably other ways to build a solution. Any thoughts on any existing solutions to this problem that I may be missing? And if there isn't an existing solution in the gem, any thoughts on which of the above approaches (or any others you can think of) would be most desirable?

**Comment by arunagw** [comment]
Hello @rylwin thanks for pointing this issue. I think as API accepts `nil` and `""` values to clear out the values for the keys we should allow that form the gem also.

**Comment by arunagw** [comment]
I am in favour of having a new method to update all attributes as modifying existing methods might break current applications as people might be expecting that `nil` or `""` attributes are skipped automatically.

**Comment by arunagw** [comment]
Done in #299
