### ISSUE TITLE
Support hosted authentication

### ISSUE THREAD

**Issue by pfista** [nylas/nylas-ruby#223]
Add support for Hosted Authentication with a helper `url_for_authentication` method that returns a url that the user can be redirected to login through Nylas' Hosted Authentication flow.

**Comment by kyletolle** [comment]
Hi @pfista. It was me and my team that asked for guidance on how to use Nylas Hosted Auth with v4 of the gem. The methods `url_for_authentication` and `token_for_code` are both used by our existing code which used v3.2.0, but these two methods don't seem to exist in v4. Thanks for the help in figuring out what changes we need to make to be able to use the Hosted Auth flow with v4.

**Comment by arunagw** [comment]
Done in #292
