### ISSUE TITLE
Specifying scopes on v3.2.0 of gem

### ISSUE THREAD

**Issue by ubermensch** [nylas/nylas-ruby#226]
Hi there,

I'm trying to configure granular scopes for our Google users through our Nylas app: https://docs.nylas.com/docs/google-granular-scopes-code

We're currently using `v3.2.0` of the gem and would like to avoid upgrading if possible for now. Any way to use the `nylas-ruby` SDK to specify a particular set of scopes on authentication?

Thanks in advance!

**Comment by arunagw** [comment]
@ubermensch Do you still want to have support for granular scopes on `v3.2`? 

We have bumped the major version and latest release is `v4.6.5` and we recommend it to upgrade to this version to have all latest features from the API in SDK.

**Comment by arunagw** [comment]
Closing this issue for now. Please reopen this if you still want to have this supported. Thanks
