### ISSUE TITLE
No way to notify participants on create for events

### ISSUE THREAD

**Issue by pk1m** [nylas/nylas-ruby#229]
When creating an event, no way to add query params.
execute takes query params
https://github.com/nylas/nylas-ruby/blob/master/lib/nylas/http_client.rb#L72

but create does not allow it to be passed
https://github.com/nylas/nylas-ruby/blob/master/lib/nylas/model.rb#L43

api should allow us to pass in notify_participants queyr param
https://docs.nylas.com/reference#post-event

**Comment by rylwin** [comment]
@pk1m here's the workaround we're using:

```
        external_event = nylas_client.events.new(params)
        result = external_event.execute(
          method: :post,
          payload: external_event.attributes.serialize,
          path: "#{external_event.resources_path}?notify_participants=true",
        )
```

**Comment by arunagw** [comment]
Closing as #284 is merged in master and this feature will be available in next release. thanks.
