### ISSUE TITLE
An unexpected error occurred during authentication 

### ISSUE THREAD

**Issue by MeterSoft** [nylas/nylas-ruby#241]
I get error when trying connect to outlook uses ruby gem

Nylas::InternalError: An unexpected error occurred during authentication.
from /home/bohdan/.rvm/gems/ruby-2.4.1/gems/nylas-4.6.0/lib/nylas/http_client.rb:166:in `handle_anticipated_failure_mode'

how i can know about details?

P.S. Google connected as well

**Comment by BenLloydPearson** [comment]
Hi @MeterSoft,

Have you been able to authenticate any accounts at all? Or are you only having problems with Outlook and Google?

Something that might help you is our example app that demonstrates how to handle user authentication: https://github.com/nylas/nylas-ruby/tree/master/examples/authentication
