### ISSUE TITLE
File Attachment Doesn't download

### ISSUE THREAD

**Issue by aballester92** [nylas/nylas-ruby#252]
A prospect is trying to download and display an attachment but keeps running into an error with the Ruby sdk.

This is his code: 
`file = Nylas.files.find(params[:id])
type = MIME::Types[file.content_type].first.extensions.first
send_file file.download.path, type: type, disposition: 'inline'`

**Comment by arunagw** [comment]
@aballester92 can you explain a bit more what kind of error you are getting.

I can see that using `file.download.path` actually downloads the file and returns the path to Temp file.

**Comment by arunagw** [comment]
Closing this issue for now. Please reopen this if it's still an issue. Thanks.
