### ISSUE TITLE
attributable.rb:26:in `assign': wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by viral810** [nylas/nylas-ruby#257]
When attempting to call `api.messages.find(id)`, In rare scenarios we get this exception

```
File /usr/local/bundle/gems/nylas-4.6.3/lib/nylas/model/attributable.rb line 26 in assign
File /usr/local/bundle/gems/nylas-4.6.3/lib/nylas/model.rb line 63 in reload
File /usr/local/bundle/gems/nylas-4.6.3/lib/nylas/collection.rb line 130 in find_model
File /usr/local/bundle/gems/nylas-4.6.3/lib/nylas/collection.rb line 117 in find
```
Looking at this method here https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/model/attributable.rb#L26, because of the splat operator, if arguments are not passed in as keyword arguments, it will raise the exception.

Looking at the next line https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/model.rb#L63, it seems like there could be an invalid response causing to be passed in invalid value and causing the exception to happen.

Can we please look into this and have it handle more gracefully?

**Comment by UnlimNET** [comment]
The same problem:

`api.messages.find(id)` **wrong number of arguments (given 1, expected 0)**

**Comment by bmulholland** [comment]
Yeah I just spent 10 minutes assuming my code had a bug. Glad I remembered that I'd seen this before or I'd have wasted more time.

**Comment by mchristen** [comment]
I'm using version 4.6.4 of this gem and still experiencing this exception from time to time. 

Any ideas?

**Comment by nickbair-nylas** [comment]
Hi @mchristen, can you reach out to us at `customeronboarding@nylas.com` so we can review?
