### ISSUE TITLE
Cannot download a file that was fetched from a message association

### ISSUE THREAD

**Issue by bmulholland** [nylas/nylas-ruby#258]
Calling download on a file that was fetched from a message fails. This is common if you're looping over a set of messages and then downloading the files from there.

Workaround is to do a fresh file fetch.

This code fails:
```
2.7.2 :021 > nylas.messages.find('ID_FOR_MESSAGE_WITH_ATTACHMENT').files.first.download
Traceback (most recent call last):
        2: from (irb):20
        1: from (irb):21:in `rescue in irb_binding'
NoMethodError (undefined method `get' for nil:NilClass)
Did you mean?  gem
```

This works, but is more complex and less efficient:
```
2.7.2 :023 > nylas.files.find(message.files.first.id).download
 => #<Tempfile:/var/folders/vz/wfs0t4g55xn0sjpnmf6d9jfc0000gn/T/Services Contract - Hellsgate - Reply With Redlines Accepted.docx20201012-70192-ypr2bz>
```

**Comment by arunagw** [comment]
I can confirm this bug.

**Comment by arunagw** [comment]
@bmulholland this has been fixed in main branch and will be available in next release. Thanks for reporting this.
