### ISSUE TITLE
HTTP timeouts

### ISSUE THREAD

**Issue by wilddima** [nylas/nylas-ruby#259]
Hi! We use Nylas in sync way to check the number of emails for clients. Some time ago we faced issues when Nylas had troubles and stopped responding to our requests. Because of this timeouts, we reached out to the limits of threads for our server. Could you please explain, why these timeouts are so big?
```
ENDPOINT_TIMEOUTS = {
      "/oauth/authorize" => 345,
      "/messages/search" => 350,
      "/threads/search" => 350,
      "/delta" => 3650,
      "/delta/longpoll" => 3650,
      "/delta/streaming" => 3650
    }.freeze
timeout = ENDPOINT_TIMEOUTS.fetch(path, 230)
```
https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/http_client.rb#L21-L26
Default 4 minutes is already a huge time, but more than one hour for "delta" endpoints is really too much.

If it's okay for you, I can send you PR with adding the ability to configure these timeouts, if you don't want to change it by default.

**Comment by moigagoo** [comment]
@wilddima hey, I've discussed this issue with people from Nylas. They say the PR would be of interest to them and they would merge it should it be submitted.

So, if you have the code ready and some spare time, feel free to submit the PR :-)

**Comment by arunagw** [comment]
Hey @wilddima thanks for reporting this. If you have a work in progress code I would love to take a look. A configuration sounds good to me for these defaults.

**Comment by mrashed-dev** [comment]
@wilddima Thanks for opening this issue, we are now tracking this feature request internally and will address it in a future release! We will tag this issue once it is released, thank you!

**Comment by dinsley** [comment]
Where did this land internally? It's still an issue and a sixty minute timeout for an end-point is dangerous to users of this client. Is there a reason that the non-long polling ones are set so high, and is there an expectation that users of the service should expect or see incredibly long response times?

We're seeing up to 50 minute requests to a single paginated end-point on the deltas end-point.
