### ISSUE TITLE
Add support for calendars/free-busy

### ISSUE THREAD

**Issue by oluosiname** [nylas/nylas-ruby#260]
Hello, we use Nylas for a couple of things around calendar synchronisation but noticed that the endpoint `POST /calendars/free-busy` is not yet implemented for the ruby sdk. I would like to work on this and add it so future users can have it available

**Comment by arunagw** [comment]
@oluosiname did you get a chance to work on this? Do you have any work in progress branch which can be picked up for future?

**Comment by arunagw** [comment]
It has been implemented in #288

**Comment by arunagw** [comment]
We now have support for `/calendars/free-busy` endpoint and it will be available in next release.
