### ISSUE TITLE
NoMethodError when parsing 504 responses for /send endpoint

### ISSUE THREAD

**Issue by sveinn** [nylas/nylas-ruby#261]
Hi,

Occasionally we will receive a 504 from Nylas, in those cases the client gem raises a `NoMethodError` as opposed to an `APIError`. 

Relevant parts of stack trace:

```ruby
"NoMethodError",
"undefined method `merge' for <RestClient::Response 504 \"<!DOCTYPE h...\">:RestClient::Response",
"/srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/new_message.rb:28:in `send!'",
"/srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/api.rb:131:in `send!'"
```

Let me know if more information is needed to reproduce the issue. Thanks!

**Comment by joshkestenberg** [comment]
Just seconding this: Calling the `send!` function raises a `NoMethodError`. We've resorted to retrying the process on `NoMethodError`, but that's not the best workaround.

**Comment by arunagw** [comment]
Thanks for reporting issue. I have just given this a try on latest version of gem. Can you please try it with latest version of gem.

I can see that it might be an issue before version v4.6.4 but on latest it should be ok.

**Comment by arunagw** [comment]
Closing this for now as this issues should be fixed on latest version of gem. Please report back here if it's still an issue. thanks
