### ISSUE TITLE
Warning: Nylas::Deltas#each at /usr/local/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method NilClass#each

### ISSUE THREAD

**Issue by viral810** [nylas/nylas-ruby#263]
```
/usr/local/lib/ruby/2.6.0/forwardable.rb:230: warning: Nylas::Deltas#each at /usr/local/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method NilClass#each
 
undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	from /usr/local/lib/ruby/2.6.0/forwardable.rb:224:in `map'
```

Randomly got a failure when called `api.deltas.where(filters)` method.

**Comment by arunagw** [comment]
@viral810 I was looking at this issue and not be able to reproduce this. Can you share more details or a code snippet to demonstrate the failure?

**Comment by viral810** [comment]
@arunagw unfortunately I am not working with the library actively anymore. I noticed that this wasn't a consistent error but rather occurred at a random intervals.

I'd suggest trying to reproduce in tests by mocking the API response since it is more likely to do with SDK receiving API response in unknown format and producing these errors. If you can't reproduce it, feel free to close it as I might not be able to help with reproduction.
