### ISSUE TITLE
Request timeout errors should be wrapped with Nylas namespace

### ISSUE THREAD

**Issue by nickbair-nylas** [nylas/nylas-ruby#272]
When a request times out, the error that is raised is not part of the Nylas namespace.  This makes rescuing the error difficult for users of the gem.

`Timed out reading data from server (RestClient::Exceptions::ReadTimeout)`

**Comment by bmulholland** [comment]
This is a nice quality-of-life fix that makes for a well-polished gem! I'm a big fan of this sort of work.

**Comment by arunagw** [comment]
This has been fixed by #303.
