### ISSUE TITLE
Methods that should only return ``Collection`` type return ``RestClient::Response`` instead of raising exceptions on 502

### ISSUE THREAD

**Issue by moigagoo** [nylas/nylas-ruby#274]
Methods that we expect to return only [collections](https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/collection.rb), e.g. api.threads.search(params).execute, also return ``RestClient::Response`` in case of error.

It would be more convenient for us to get an exception in this case because the way it's done now, we can't reliably process the response and have to expect ``RestClient::Response`` just in case.

**Comment by arunagw** [comment]
@moigagoo I would say it should return errors with `Nylas` namespace instead of `RestClient::Response` as suggested in #272 

What do you think?

**Comment by moigagoo** [comment]
@arunagw if by returning errors you mean raising exceptions, then yes, this is exactly what I'm asking for. The exception should belong to the Nylas namespace, of course.

**Comment by arunagw** [comment]
@moigagoo can you please give us a code snippet or example code to try this out? I can see that error raised in https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/http_client.rb#L177-L183 for the known errors.

**Comment by arunagw** [comment]
This has been fixed by #303. Please give it a try if you can. 

thanks
