### ISSUE TITLE
Uninitialized constant Inbox::Calendar when running RSpec in Rails app

### ISSUE THREAD

**Issue by hartator** [nylas/nylas-ruby#28]
Thanks for great API!

Nylas works fine in our development server but I got `Uninitialized constant Inbox::Calendar` when running the specs for our Rails app. (`bundle exec rspec spec`)

I've tried a to rebuild the gem bundle, update to last Nylas `0.18.1`... but I don't seem to be able to run the specs. Any ideas?

Full traceback:

    ➜  App-Rails git:(add-nylas-for-email) ✗ bundle exec rspec spec
    /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nylas-0.18.1/lib/namespace.rb:91:in `<class:Namespace>': uninitialized constant Inbox::Calendar (NameError)
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nylas-0.18.1/lib/namespace.rb:23:in `<module:Inbox>'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nylas-0.18.1/lib/namespace.rb:21:in `<top (required)>'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nylas-0.18.1/lib/nylas.rb:5:in `<top (required)>'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/config/application.rb:16:in `<top (required)>'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/config/environment.rb:2:in `require'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/config/environment.rb:2:in `<top (required)>'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/spec/spec_helper.rb:54:in `require'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/spec/spec_helper.rb:54:in `block in <top (required)>'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spork-0.9.2/lib/spork.rb:24:in `prefork'
    	from /Users/hartator/rallyhood/Rallyhood-Rails/spec/spec_helper.rb:47:in `<top (required)>'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `require'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `block in requires='
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `each'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1280:in `requires='
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `each'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration_options.rb:21:in `configure'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:101:in `setup'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
    	from /Users/hartator/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
    	from /Users/hartator/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
    	from /Users/hartator/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'

**Comment by khamidou** [comment]
Hi @hartator,

Did you try adding a `require 'nylas'` to `/Users/hartator/rallyhood/Rallyhood-Rails/spec/spec_helper.rb`?

k

**Comment by hartator** [comment]
Yes, already tried it. Getting the same error.

**Comment by hartator** [comment]
Ok, finally found out why. We had `module Calendar` defined at `lib/calendar.rb` inside our Rails app, I guess impeaching the nylas `Inbox::Calendar` to load properly when running specs. (Weird it's only an issue with RSpec)

Renaming our module solved the problem.

Thanks for the help anyway @khamidou!

**Comment by khamidou** [comment]
np, glad you solved it!
