### ISSUE TITLE
Extract Fake API for mocking in implementation apps

### ISSUE THREAD

**Issue by bmulholland** [nylas/nylas-ruby#280]
I'd like to mock out Nylas using the same approach this test suite uses - or perhaps an improved one, using FactoryBot.

I can do that in my own code, but then I'll have to maintain it myself, and no one else would benefit from it.

Would Nylas consider a PR that extracted the FakeAPI into something that can be extended from client applications to help with testing? Any specific direction or desires from that?

**Comment by bmulholland** [comment]
Actually looks like FakeAPI isn't used for what I want - Message tests, for instance, just mock out api.execute. Still, would be nice to have some sort of mocking built in. Open to ideas on approach.

**Comment by arunagw** [comment]
Hey @bmulholland thanks for nice suggestion. We would love to see some examples how it looks before going deeper. Feel free to paste some examples just to show how it might look and then we can discuss more. I am not sure about `FactoryBot` as it will add one more dependency but if it simplifies things we are up for it.

**Comment by arunagw** [comment]
Closing this for now as we are not planning to add this very soon. @bmulholland if you have some examples please paste here. 

thanks

**Comment by bmulholland** [comment]
Yeah we're just adding these as we go, and realistically only got started a couple weeks ago.

The ideal API for this would actually be how AWS does it -- see Basic Usage here https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html

The factories we're putting together are still getting assembled as needed, and more to come. These could be included with Nylas (it would be nice!) but they'd be tied to FactoryBot, which not everyone will be using.

These currently look like:

**spec/support/factories/nylas/messages.rb**
```
FactoryBot.define do
  # https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/message.rb
  factory :nylas_message, class: "Nylas::Message" do
    transient do
      message_id { Faker::Alphanumeric.alphanumeric(number: 32) }
      thread { association(:nylas_thread) }
    end

    id { Faker::Alphanumeric.alpha(number: 32) }

    from { [association(:nylas_email_address)] }
    subject { Faker::Lorem.sentence(word_count: 3) }
    body { Faker::Lorem.paragraph }
    snippet { body[0..50] }
    date do
      Faker::Date.between(
        from: RecitalConstants::OLDEST_TIMESTAMP_TO_SCAN.ago + 1.day,
        to: 1.day.ago,
      )
    end
    headers { association :nylas_message_headers, message_id: message_id }

    thread_id { thread.id }

    files { [] }

    trait :docx_attached do
      files { [association(:nylas_file, :docx, message: instance)] }
    end

    trait :pdf_attached do
      files { [association(:nylas_file, :pdf, message: instance)] }
    end

    trait :txt_attached do
      files { [association(:nylas_file, :txt, message: instance)] }
    end

    trait :nothing_attached do
      files { [] }
    end
  end
end
```

And then our mocking for Nylas to use this, which honestly needs work and the stub_responses approach would really help with:

**spec/support/shared_contexts/mock_nylas.rb**
```
RSpec.shared_context "mock nylas" do
  let(:nylas_message) { FactoryBot.build(:nylas_message) }
  let(:nylas_messages) do
    instance_double(
      "Nylas::Collection",
      expanded: instance_double("Nylas::Collection"),
    )
  end
  let(:nylas_file) { nylas_message.files.first }
  let(:nylas_files) { instance_double("Nylas::Collection") }
  let(:fake_nylas) do
    instance_double(
      "Nylas::Client", messages: nylas_messages,
                       files: nylas_files
    )
  end

  before do
    allow(Poro::Nylas).to receive(:client).and_return(fake_nylas)

    # not set when the message is overriden to have no attachment
    if nylas_file
      allow(nylas_files).to receive(:find)
        .with(nylas_file.id)
        .and_return(nylas_file)
    end

    allow(nylas_messages).to receive(:find)
      .with(nylas_message.id)
      .and_return(nylas_message)

    allow(nylas_messages.expanded).to receive(:find)
      .with(nylas_message.id)
      .and_return(nylas_message)

    allow(nylas_messages.expanded).to receive(:where)
      .with(thread_id: nylas_message.thread_id)
      .and_return([nylas_message])
  end
end
```

Overall, like I say, getting this all working is a lot of time and effort. I wonder how others are doing this in their test suite... I imagine there's lots of duplicated work?

**Comment by bmulholland** [comment]
In terms of connection to this gem's test suite, the implementation here could probably be an extraction of some of the patterns I see. For example, [this code](https://github.com/nylas/nylas-ruby/blob/main/spec/nylas/message_spec.rb#L7) looks a lot like a Factory!

And [this code](https://github.com/nylas/nylas-ruby/blob/main/spec/nylas/message_spec.rb#L143) looks a lot like the stub_responses! The only problem with that code is it's not abstract enough - it's fine for the Nylas client tests to be mocking internals of the library, but I don't want my devs to happen to learn about the internals of Nylas just to write tests. So if this code were abstracted a level up - `Nylas::Client.stub_responses(find_message: {id: "message-1234"})` - that would be both clearer in this gem's test suite *and* something that could be made available to consumers of this gem.

**Comment by arunagw** [comment]
Thanks @bmulholland for code samples. They looks great! I agree that test suite can be improved and it requires lot of time and effort. I will add this in the list of task to be done but not sure how soon we will be able to work on this. If you want and have some time please open a PR in work in progress mode and we can continue on that.

**Comment by bmulholland** [comment]
Sure, sounds good. If I included FactoryBot in that change, would it be accepted?

**Comment by arunagw** [comment]
I think if we are going to add that as a development dependency it will be fine as user won't be getting that when using this `nylas` gem in their apps.

**Comment by mrashed-dev** [comment]
@bmulholland Thanks for bringing forward this idea! This is something that we are interested in tackling a few months down the line. If you have a PR or some code you'd like to share to kick it off, that would be fantastic!

**Comment by bmulholland** [comment]
We've only added factories in a few areas (we are building them as the need arises), and for us that's only around reading emails & files. Here's the work we've done so far: [Nylas Factories.zip](https://github.com/nylas/nylas-ruby/files/6884564/Nylas.Factories.zip)

**Comment by mrashed-dev** [comment]
@bmulholland Sorry for the very long delay on this, I've surfaced this issue via our [Nylas Roadmap](https://roadmap.nylas.com/tabs/13-in-progress/submit-idea) board. Over there if it gets picked up you will be able to track its progress. Thanks again for your continued suggestions and contributions to this SDK!
