### ISSUE TITLE
Ruby 3 compatibility issue

### ISSUE THREAD

**Issue by tneems** [nylas/nylas-ruby#289]
Found these while upgrading an application to Ruby 3, I'd submit a PR but I'm waiting on approval of the CLA.

`to_be_executed` needs to be changed to `**to_be_executed`

https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/collection.rb#L122

https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/deltas_collection.rb#L37

**Comment by arunagw** [comment]
Hello @tneems we have done some changes for Ruby 3 recently in https://github.com/nylas/nylas-ruby/pull/283 

Please give a try with latest master and see if it works. If it works we can try and do a release.

**Comment by tneems** [comment]
I got the errors on master after #283 had been merged.

**Comment by arunagw** [comment]
Yes. I can confirm this. If you want you can make a PR.

**Comment by tneems** [comment]
Sorry if I wasn't clear, I can't sign the CLA because I'm waiting on approval from my legal department.

**Comment by arunagw** [comment]
ahh ok. I have a branch ready if you want to test https://github.com/nylas/nylas-ruby/compare/fixes-for-ruby3-deltas

If this looks good we can merge this in master.

**Comment by tneems** [comment]
Yep that works, my CI passes. Are you planning a new release with ruby 3 compatibility soon?

**Comment by arunagw** [comment]
Great! Yes we are planning a release soon. Thanks for quick check.

**Comment by arunagw** [comment]
@tneems I have just merged #290 so it's good to go. Will try to do a release this week sometime. Thanks for help.
