### ISSUE TITLE
The first calendar, “Calendar”, is not a provider-backed calendar

### ISSUE THREAD

**Issue by silab** [nylas/nylas-ruby#29]
the api says "The first calendar, “Calendar”, is a provider-backed calendar.", but its actually not. The first calendar i get is this one: "title: Emailed events, desc: Emailed events, readonly: true". is there a method to get the  provider-backed calendar? i dont want to iterate over all calendars every time. you should put the provider-backed calendar first.

```
calendar_id = inbox.namespaces.first.calendars.first.id
```
gives you a read_only calendar and not the provider-backed calendar.

**Comment by khamidou** [comment]
Hi Silab,

This is actually an error in our docs.

Concerning your problem, you don't have to iterate over the calendar list every time. You could save the calendar's id to the db and use `Calendar#find` to get it back (e.g:
```ruby
cal = inbox.namespaces.first.calendars.find(calendar_id)
```

Hope this helps!

Karim

**Comment by woniesong92** [comment]
@khamidou do you have a plan to provide filtering for calendars?
