### ISSUE TITLE
RestfulModelCollection initializer being passed deprecated argument namespace_id

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#30]
https://github.com/nylas/nylas-ruby/blob/72ea654e0c043bc3ca3df14c5a7efbfb513cd467/lib/api_thread.rb#L40
https://github.com/nylas/nylas-ruby/blob/72ea654e0c043bc3ca3df14c5a7efbfb513cd467/lib/api_thread.rb#L44
https://github.com/nylas/nylas-ruby/blob/6555a7a4269cd9df70c72f6dcb9c2c19f3ad41cc/lib/calendar.rb#L12

Resulting in 'Exception: ArgumentError: wrong number of arguments (4 for 2..3)'

**Comment by jockee** [comment]
Simply removing `@namespace_id, ` in these three instances seems to do the trick.

**Comment by khamidou** [comment]
Oof, fixed in 378546585e903d11f!

**Comment by jockee** [comment]
:+1:
