### ISSUE TITLE
Method for downloading file contents

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#31]
File#download or equivalent

**Comment by jockee** [comment]
Our monkey patch looks like this: 

    class File < RestfulModel
      def download
        RestClient.get(url + '/download')
      end
    end

**Comment by khamidou** [comment]
Thanks for the bug report, @jockee. I've just fixed this in 773d3f6ed4b1b.

**Comment by jockee** [comment]
Thanks, @khamidou!
