### ISSUE TITLE
ArgumentError when sending email on Ruby 3.0

### ISSUE THREAD

**Issue by gmcabrita** [nylas/nylas-ruby#310]
**Describe the bug**

Using `Nylas::API#send!` raises an ArgumentError. This appears to happen after the actual API call since when testing I end up receiving it in my inbox.

**To Reproduce**

```ruby
> nylas_api.send!(from: [{email: "foo@example.com"}], to: [email: "bar@example.com"], subject: "Foo", body: "Bar")
ArgumentError: wrong number of arguments (given 1, expected 0)
from /opt/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nylas-5.1.0/lib/nylas/model/transferable.rb:12:in `initialize'
```

Here's the relevant backtrace:

```
/opt/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nylas-5.1.0/lib/nylas/model/transferable.rb:12:in `initialize'
/opt/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nylas-5.1.0/lib/nylas/new_message.rb:29:in `new'
/opt/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nylas-5.1.0/lib/nylas/new_message.rb:29:in `send!'
/opt/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/nylas-5.1.0/lib/nylas/api.rb:145:in `send!'
```

**Expected behavior**

An exception should not be raised in this case, since the email was successfully sent.

**SDK Version:**

Both 4.6.7 and 5.1.

**Comment by mrashed-dev** [comment]
Thanks for submitting this issue, we are taking a look at this!

**Comment by gmcabrita** [comment]
Any update on this? This is blocking us from upgrading to Ruby 3.

**Comment by mrashed-dev** [comment]
@gmcabrita We have it on the docket to address this week, I'll update you as soon as we have any updates to share.

**Comment by gmcabrita** [comment]
Thanks for fixing the issue! When should we expect the new gem version to be pushed?

**Comment by mrashed-dev** [comment]
@gmcabrita sorry for the delay on that front! We should be releasing a new gem sometime this week! Will keep you posted 😄
