### ISSUE TITLE
Nylas::JsonParseError

### ISSUE THREAD

**Issue by bmulholland** [nylas/nylas-ruby#313]
**Describe the bug**
Looks like an issue happened on the Nylas servers that caused HTML to be returned instead of JSON, and that caused a cryptic error in our app.

**To Reproduce**
Line of code that hit this was `message = nylas.messages.expanded.find(message_id)`

Error was `Nylas::JsonParseError`, due to `Yajl::ParseError`

More specifically, Yajl said:

```
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
```

**Expected behavior**
A clear error message about the root cause of the issue at Nylas (even just "Internal Server Error" would be better than this).

**Comment by mrashed-dev** [comment]
@bmulholland thanks for opening this issue we will take a look at it!

**Comment by bmulholland** [comment]
Thank you!
