### ISSUE TITLE
Delta header

### ISSUE THREAD

**Issue by tchiarato** [nylas/nylas-ruby#314]
**Describe the bug**
`Delta` doesn't have the attribute `#headers` which makes it difficult to access information like `In-Reply-To` or `References`.
The only option to access these fields is through the `#object_attributes` which is a raw version of the API response.

However, due to its raw format and difference in style from objects like `Message` (which has `#headers`) it creates a layer of complexity to read _headers_ information since they are different in style from `Message#headers`.

**To Reproduce**
```ruby
# 1. instanciate API
api = Nylas::API.new( app_id: <client_id>, app_secret: <client_secret>, access_token: <access_token>)

# 2. execute `/deltas` api
deltas = api.deltas.expanded.where(cursor: <cursor>)

# 3. execute `/messages` api
messages = napi.messages.expanded.where({ any_email: 'my@email.com' })

# 4. compares the difference on headers format style
deltas.deltas.first.object_attributes[:headers].keys == messages.first.headers.to_h.keys
```

An example of Delta vs Message headers keys
```ruby
# Message keys
[:in_reply_to, :message_id, :references]

# Delta keys
[:"In-Reply-To", :"Message-Id", :References, :object_attributes]
```

**Expected behavior**
The expanded version of objects should have the same format independently whether they are `Deltas` or `Messages`.

**SDK Version:**
5.1.0

**Comment by mrashed-dev** [comment]
@tchiarato Thanks for opening this issue, we will investigate!

**Comment by tchiarato** [comment]
Hey @mrashed-dev, I created a proposal [PR](https://github.com/nylas/nylas-ruby/pull/315) to add this functionality.

Could you please give me your two cents? :)
I really appreciate your help.

Cheers

**Comment by mrashed-dev** [comment]
Thank you for your PR, it's a fantastic first-time contribution! It's merged into the main branch and will be included in the next release! 🚀
