### ISSUE TITLE
Directly accessing a message's `files` JSON object

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#32]
Currently `files` is not a parameter, but a `RestfulModelCollection` of `File`s. 

Would be nice if it was possible to just access the small JSON object, thus not sending any requests.

As far as naming goes, I've got nothing. :)

**Comment by jockee** [comment]
By replacing `message.files` with this collection of `File`s, the `content_id` -- which is provided when retrieving a message, but not when retrieving a file - is lost.

**Comment by jockee** [comment]
By replacing message.files with this collection of Files, the content_id -- which is provided when retrieving a message, but not when retrieving a file - is lost.

**Comment by jockee** [comment]
The possible solutions I see are:

1. Decorate the `File` objects with `content_id`s when retrieved through the messages endpoint.
2. Provide access to both the original `messages.files` object and the collection of `File`s. 

If you tell me which one you prefer, I'll submit a pull request.

**Comment by khamidou** [comment]
Hi @jockee,

I'm not sure I understand your use case. I'll be happy to discuss it in our [slack channel](https://nylas-chat.slack.com) though. 

Karim

**Comment by khamidou** [comment]
As discussed on Slack, we're going to fix this upstream.

**Comment by khamidou** [comment]
Fixed in https://github.com/nylas/sync-engine/commit/93bcc7586ac49fbacea38088272c009730be05b8.
