### ISSUE TITLE
[Bug] Can't Deserialize Messages When Get a Thread with Expanded View

### ISSUE THREAD

**Issue by GuYifan** [nylas/nylas-ruby#321]
**Describe the bug**
When get a thread via `/threads/{thread_id}?view=expanded`, it returns an array of messages instead of an array of message IDs.

{...
messages: [
{
...
message_id: 'xxx',
...
},
]
...}

But when try to do it through the SDK, it returns nil.

**To Reproduce**
Some steps involved to reproduce the bug and any code samples you can share.
```
api.threads.find(thread_id, expanded: true).dig(:messages)
=> nil
```

**Expected behavior**
Should deserialize messages and returns an array of messages.

**SDK Version:**
5.2.0

Fix: https://github.com/nylas/nylas-ruby/pull/319

**Comment by mrashed-dev** [comment]
Great find and thanks for the PR! Sorry I couldn't get to it sooner but it's merged in now. Should be included in the next Ruby release, coming sometime this week!
