### ISSUE TITLE
Can't attach file to draft

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#33]
I think `file_ids` is missing as a parameter and it needs to have a default value of `[]`.

    NoMethodError: undefined method `push' for nil:NilClass
    from /usr/src/app/config/initializers/nylas_extensions.rb:27:in `attach'

**Comment by jockee** [comment]
Our current monkey patch:

    class Draft < Message
      parameter :file_ids

      def attach(file)
        file.save! unless file.id
        @file_ids ||= []
        @file_ids.push(file.id)
      end
    end

**Comment by khamidou** [comment]
Thanks for the bug report! I fixed this in abe28f03.

**Comment by jockee** [comment]
Thank you!
