### ISSUE TITLE
Proposal: Add `Message#files?`

### ISSUE THREAD

**Issue by jockee** [nylas/nylas-ruby#40]
As it is in both Nylas' and its users' best interest to minimize the number of requests, I propose adding a method `#files?` to `Message` in order to remove the need to hit the files endpoint in order to know whether the message actually has files attached to it.

**Comment by khamidou** [comment]
Thanks for the request. I've just fixed this in eddf0e6.

**Comment by jockee** [comment]
Thanks @khamidou!
