### ISSUE TITLE
Constraint `per_page` not editable

### ISSUE THREAD

**Issue by jjf21** [nylas/nylas-ruby#412]
Hi,
I saw that there is a `per_page` attribute (default to 100) on the collection constraint.
Currently it isn't possible to edit this `Constraint` object (so neither the `per_page` attribute)

Would it be possible to add a parameter for this attribute ? 
Maybe add this parameter to the client [Nylas::API#client](https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/api.rb#L22) and pass it to all endpoints ?

Thanks

**Comment by mrashed-dev** [comment]
@jjf21 Thank you for opening this feature request! Can you expand a bit more on the purpose of changing/setting the `per_page` attribute? If you pass in a limit for a list call, we will use that for pagination otherwise it will default to 100 as that is the API default. Thanks!
