### ISSUE TITLE
Error when calling `messages.search().count`

### ISSUE THREAD

**Issue by hudxy** [nylas/nylas-ruby#416]
**Describe the bug**
Not sure if this is a bug or feature request but calling `.count` on `SearchCollection` object results in the error `Nylas::InvalidRequest: Unexpected query parameters set(['view'])`

**To Reproduce**
Some steps involved to reproduce the bug and any code samples you can share.
```
> Nylas::API.new(app_id: <app_id>, app_secret: <app_secret>, access_token: <access_token>).messages.search(<search_string>).count
Nylas::InvalidRequest: Unexpected query parameters set(['view'])
```

**Expected behavior**
This method should return the number of messages found from the search query.

**SDK Version:**
5.14.0

**Additional context**
Related to: https://github.com/nylas/nylas-ruby/issues/378

**Comment by mrashed-dev** [comment]
@hudxy Thanks for opening this issue, we will investigate and follow up with any update!
