### ISSUE TITLE
Scheduling Page creation not supported?

### ISSUE THREAD

**Issue by drewlustro** [nylas/nylas-ruby#417]
Hello!

I'm trying to create a **Schedule Page** programmatically (smart integration).

I want to make a scheduling page that allows a guest to book time on a team's calendar (round robin availability). I don't necessarily want to create one programmatically, but it seems like the only way to do round robin.

The documentation has code samples as cURL request, but I don't see this functionality/endpoint supported by `nylas-ruby` ??

https://developer.nylas.com/docs/scheduler/schedule-editor/smart-integration/#post-example-request-create-a-scheduling-page

### Imagined flow

- guest lands on my rails endpoint
  - endpoint sends request to Nylas to generate a scheduling page for sales team calendar set [A, B, C]
- rails redirects to Nylas hosted scheduling page
- guest schedules time with person A, B, or C
  - webhook hits rails server, I make note of it
- callback brings them back to my rails app

Do I have the mental model wrong?

There's no GUI on Nylas to create a round-robin scheduling page once.

If there was, I'd just create one scheduling page that I could embed for all guests.

**Comment by jimmypoulsen** [comment]
@drewlustro nylas-ruby does in fact support the manage/pages endpoint. Take a look here: https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/scheduler.rb.

It's as simple as doing

```ruby
nylas_client.scheduler.create(access_tokens: [<ACCESS_TOKEN>, <ANOTHER_ACCESS_TOKEN>])
```

**Comment by drewlustro** [comment]
Thanks @jimmypoulsen!
