### ISSUE TITLE
Fetching contact's picture raises `Encoding::UndefinedConversionError`

### ISSUE THREAD

**Issue by mc-bro** [nylas/nylas-ruby#422]
**Describe the bug**
Fetching contact's picture raises `Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8)`

Similar issue was fixed some time ago here: https://github.com/nylas/nylas-ruby/pull/193

The solution is to pass encoding argument when creating a Tempfile:
```
Tempfile.new(encoding: 'ascii-8bit')
```

**Comment by mrashed-dev** [comment]
Thanks for opening the issue @mc-bro, we will fix this and include it in a future release!
