### ISSUE TITLE
Nylas Ruby SDK v6 rest-client dependency version update

### ISSUE THREAD

**Issue by loomchild** [nylas/nylas-ruby#485]
I am migrating an application SDK from v5 to v6 to support API v3, and noticed that you upgraded `rest-client` dependency from `">= 2.0", "< 3.0"` to `"~> 2.1", "< 3.0"`. Our app uses another gem that depends on `rest-client` `<= 2.0.2`, which creates a conflict.

Could you please share why this dependency was upgraded and whether it can be potentially downgraded (upstream, or by creating a fork if necessary)? I realize that this dependency is 5 years old, and I have already reached out to maintainers of the other gem to understand why an outdated version is required, but I'd also like to know your reasoning to decide what to do.

**Comment by mrashed-dev** [comment]
Hey @loomchild Thanks for opening this issue. This was one of the many changes and dependency upgrades we needed to do that was a result of two things; adding more dependencies which caused conflicts on what we had previously, and setting a minimum supported Ruby version (3.0). I _believe_ that downgrading this gem upsteam will break some of our workflows like our mocks, etc. but potentially it may work for you if you fork and use it that way.

**Comment by loomchild** [comment]
Thanks for your reply.

I understand that you won't downgrade, so I will close this issue. Feel free to share more details about broken workflows (your tests seem to work for me just fine). 

BTW, since you are supporting only Ruby 3, perhaps switching to modern networking gem like Faraday instead of rest-client would be a better option.
