### ISSUE TITLE
Add `query_params` to the `folders.list(..)` method

### ISSUE THREAD

**Issue by neilberget** [nylas/nylas-ruby#488]
There is no way to retrieve a second page of folders since the [list method](https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/resources/folders.rb#L18) in Folders only takes the identifier parameter.

If the query_params argument is added (for example https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/resources/messages.rb#L30 we'd be able to pass in a cursor for pagination.

We have worked around it by building the api call ourself but would help clean things up if this was made to be consistent with the other list methods.

I do see the cursor is already being returned, so only allowing it to be passed in via query_params should solve the issue.

**Comment by mrashed-dev** [comment]
@neilberget Thanks for posting, will add this!
