### ISSUE TITLE
Fetching a folder should support select field

### ISSUE THREAD

**Issue by bmulholland** [nylas/nylas-ruby#499]
https://developer.nylas.com/docs/api/v3/ecc/#get-/v3/grants/-grant_id-/folders/-folder_id- has a select option

https://github.com/nylas/nylas-ruby/blob/main/lib/nylas/resources/folders.rb#L31 does not

**Comment by bmulholland** [comment]
(Hi @AaronDDM! Hope you're well :) )

**Comment by SubashPradhan** [comment]
Closing this issue, the fix has been released in v6.2.1.
