### ISSUE TITLE
Support Custom content_id for Attachments in multipart/form-data

### ISSUE THREAD

**Issue by KJambo** [nylas/nylas-ruby#505]
Currently, the Nylas Ruby SDK does not allow users to set a custom `content_id` for attachments when sending emails as `multipart/form-data`. This limitation makes it difficult to use inline attachments, such as embedding images directly in the email body (e.g., `<img src="cid:custom_content_id" />`).

In the current implementation, the SDK automatically assigns attachment names like `file0`, `file1`, etc., when constructing the form request([source](https://github.com/nylas/nylas-ruby/blob/9d6db9eb4d40d01146ee1ed2dc46293e584a2c85/lib/nylas/utils/file_utils.rb#L46)).  While these names are internally treated as `content_id` by the Nylas API and can technically be used (e.g., `<img src="cid:file0" />`), users have no control over these identifiers. This lack of customization limits the flexibility and usability of inline attachments.

I would like the SDK to support user-defined `content_id` for attachments. Specifically:

- Allow developers to specify a `content_id` for each attachment when constructing the email.
- Use the provided `content_id` in place of the default names (file0, file1, etc.).
- If no `content_id` is provided, fallback to the current behavior to ensure backward compatibility.

**Comment by SubashPradhan** [comment]
The fix has been released in v6.2.2. Thanks for raising this issue.
