### ISSUE TITLE
Wrap Exceptions

### ISSUE THREAD

**Issue by brettgerry** [nylas/nylas-ruby#52]
@khamidou Per your recommendation:

```
begin
   draft.send!
rescue Nylas::NetworkError => e
  puts "Underlying network error"
  puts "Original exception:"
  puts e.original_exception # => original RestClient exception
rescue Nylas::APIError => e
   puts "Failed with error: #{e.message}"
end
```

Would possibly need to create a major version rev for backward compatibility issues.

**Comment by stevenharman** [comment]
Do note that as of Ruby 2.1 we could `fail` with a `Nylas`-specific exception and Ruby will set an original exception as the `#cause`.

See [Exception Causes in Ruby 2.1](http://devblog.avdi.org/2013/12/25/exception-causes-in-ruby-2-1/) for more details.

**Comment by zspencer** [comment]
@khamidou - is this still something you'd like done, or is it abandonable?

**Comment by zspencer** [comment]
This appears to be done
