### ISSUE TITLE
Token_for_code returning only access_token

### ISSUE THREAD

**Issue by Bartuz** [nylas/nylas-ruby#56]
My app will be using your webhooks which means I need to have `account_id` assigned to every user (so I know which user should have an event evaluated, right?).

With this line of code: https://github.com/nylas/nylas-ruby/blob/master/lib/inbox.rb#L143 I only get access_token and there is no way I can retrieve the `account_id`. 

I think there should be method which saves this [json](https://github.com/nylas/nylas-ruby/blob/master/lib/inbox.rb#L142) as `@instance_variable` and provide methods like `token_for_account_id` / `token_for_provider` / `token_for_access_token` which will just access saved json instead of calling your API twice (which actually raises unexpected error now - https://github.com/nylas/nylas-ruby/issues/55)

**Comment by khamidou** [comment]
Hi @Bartuz, thanks for the bug report! Have you tried getting the account_id by using the `#account` API? (i.e: by doing something like this in your app:
```ruby

def get_token
  nylas = Nylas::API.new(APP_ID, APP_SECRET, nil)
  token = nylas.token_for_code(params[:code])
end

get '/api_callback'
  token = get_token
  nylas = Nylas::API.new(APP_ID, APP_SECRET, token)
  account_id = nylas.account.id
end
```)

**Comment by Bartuz** [comment]
It makes another API request. 

We just use kind of monkey patched your method:

```
  def token_for_code_and_account_id(code)
    data = {
        'client_id' => app_id,
        'client_secret' => app_secret,
        'grant_type' => 'authorization_code',
        'code' => code
    }

    ::RestClient.post("https://#{@service_domain}/oauth/token", data) do |response, request, result|
      json = Inbox.interpret_response(result, response, :expected_class => Object)
      return [json['access_token'], json['account_id']]
    end
  end
```

**Comment by khamidou** [comment]
I see what you mean. This is something we may fix in the future, but right now I'd prefer keeping this API simple.

Karim

**Comment by Bartuz** [comment]
This is very weird but `json['account_id'] != Nylas::API.new(APP_ID, APP_SECRET, token).nylas.account.id`. 

I've been deleting and adding the same account many times. Maybe that has broke something on your side.

**Comment by khamidou** [comment]
Oh, I see. This is a tiny edge case we didn't think of when implementing the [namespace->account transition](https://nylas.com/kb/namespaces-migration). I have a fix in the works, in the meantime, you'll have to use `#account` --- it returns the correct result.

**Comment by woniesong92** [comment]
Hey! I also prefer to receive `account_id` at the same time as `access_token`. Would you guys accept a PR?
