### ISSUE TITLE
Moving message to folder

### ISSUE THREAD

**Issue by g3ortega** [nylas/nylas-ruby#57]
i was trying to move a message using the sample in the docs:

``` ruby
trash_id = 'ds36ik7o55gdqlvpbrjbg9ovn'
message.folder = trash_id
message.save!
```

And i got this exception:

```
NoMethodError: undefined method `id' for "b8n1of68aixksz3o84qstro7i":String
from /Users/sample/.rvm/gems/ruby-2.2.0/gems/nylas-1.1.0/lib/message.rb:64:in `as_json'
```

I was reviewing the code and the problem originates in this method:

``` ruby

    def as_json(options = {})
      hash = {}

      # unread, starred and labels/folder are the only attribute
      # you can modify.
      if not @unread.nil?
        hash["unread"] = @unread
      end

      if not @starred.nil?
        hash["starred"] = @starred
      end

      if not @labels.nil? and @labels != []
        hash["labels"] = @labels.map do |label|
          label.id
        end
      end

      if not @folder.nil?
        hash["folder"] = @folder.id
      end

      hash
    end
```

Apparently an object of type Thread is expected, because the id is asked. I was also trying with labels and I have the same issue. On the other hand, i think the use of 'unless' instead of 'if not' would be more readable in a ruby context :smile: 

I can help with this issue, if it's actually is one, and not an error in the docs, and also I can help with some refactoring and optimizations.

**Comment by zspencer** [comment]
Yeah, the interface for setting a folder and / or label is a bit confusing.

Right now, we expect  `folder` to be an instance of `Nylas::Folder`, however we don't do any casting or coercing into that type. 

I think it would be reasonable to update the examples to make that explicit.
