### ISSUE TITLE
OSX El Capitán: `gem install nylas` fails out of the box.

### ISSUE THREAD

**Issue by fbartho** [nylas/nylas-ruby#59]
To work around it, I needed to run the following commands:
```
brew install openssl
sudo gem install eventmachine -- --with-cppflags="-I$(brew --prefix openssl)/include" --with-ldflags="-L$(brew --prefix openssl)/lib"
sudo gem install nylas
```

From what I understand, openssl was pulled from OSX's shared libraries in El Capitán. For a variety of reasons, brew installs openssl privately, this necessitates the cppflags & ldflags settings when installing eventmachine which depends on openssl.

**Comment by khamidou** [comment]
Hi @fbartho. Thanks for the bug report and for finding a workaround! Are you using the system Ruby or a ruby version manager (rvm, rbenv or chruby)?

**Comment by fbartho** [comment]
System Ruby

**Comment by khamidou** [comment]
This is weird, we tried reproducing this issue locally but couldn't. @fbartho Did you happen to upgrade from Yosemite?

**Comment by fbartho** [comment]
Yes, this user account upgraded from Yosemite. (I did restore the machine from timemachine backup on to new hardware, however, so maybe it counts as a clean install of El Capitán for system files?)

**Comment by khamidou** [comment]
It seems like there's not much we can do right now --- El Capitan is very new and there's no "blessed" solution right now. I've added a [workaround to the README though](https://github.com/nylas/nylas-ruby#macos-1011-el-capitan-note), though.
