### ISSUE TITLE
more parameters on thread?

### ISSUE THREAD

**Issue by jaunkst** [nylas/nylas-ruby#62]
https://github.com/nylas/nylas-ruby/blob/master/lib/api_thread.rb

can we include parameters like has_attachments, starred, and unread ? 

I see I can access them from the raw_json hash

**Comment by khamidou** [comment]
Hi @jaunkst, thanks for the bug report! This is now fixed with https://github.com/nylas/nylas-ruby/commit/ca023e34b7b31122b3972cf4c22f351e6f9c7a7d.
