### ISSUE TITLE
Get extension of of file object

### ISSUE THREAD

**Issue by Bartuz** [nylas/nylas-ruby#65]
We can get `filename` of file here https://github.com/nylas/nylas-ruby/blob/master/lib/file.rb#L7, but if we want to discover what extension it is we have to run regexp vs filename on our own. Would be great to add extension parameter to file class

**Comment by khamidou** [comment]
Well, you can rely on the mime/type for this, unless I'm missing something?

**Comment by zspencer** [comment]
One thing to keep in mind with extension parsing is that there really isn't a "good" way to do it. I agree with @khamidou that relying on the `content_type` field for making decisions instead of the extension.

For instance, is the `foo.bar.baz` file a `.baz` file or a `.bar.baz` file?
