### ISSUE TITLE
Using a local sync engine

### ISSUE THREAD

**Issue by mguymon** [nylas/nylas-ruby#75]
How does one generate the app id and secret when running a local sync engine?

and Thx for providing a ruby gem.

**Comment by khamidou** [comment]
Hi @mguymon! 

We have a couple snippets about how to use the Ruby SDK with a local sync engine: https://github.com/nylas/nylas-ruby#open-source-sync-engine

By the way, don't forget that you shouldn't be exposing the sync-engine API to the general public --- you'll have to write your own auth.

Finally, to make sure to get a timely reply to support requests, send an email to support@nylas.com.

Regards,

Karim
