### ISSUE TITLE
Namespace missing

### ISSUE THREAD

**Issue by jchatel** [nylas/nylas-ruby#77]
I included the gem and many things went bad because I already have Inbox as a model in my application,

Nylas modules are not namespaced! so the gem "pollute" the global namespace.

Can you please namespace the modules used in the gem? Not only it's good practice but kind of a must have because that's really not cool to screw someone else global namespace like that.

**Comment by Uelb** [comment]
+1
Some RestClient requests I was using in my app got some headers overwritten by the nylas ones and I got many issues because the User Agent was not the one I expected

**Comment by pfista** [comment]
This has been fixed as of 73165ec02146719aef9c578762e36aa9832ce97a

Upcoming release 3.0.0 removes all references to Inbox and instead will only work with `Nylas`
