### ISSUE TITLE
Dependencies not versioned

### ISSUE THREAD

**Issue by jchatel** [nylas/nylas-ruby#78]
This make the gem unsuited for production. There is no version specified in the dependencies.

This means that deploying new code in production can break if em-http-request or yajl-ruby introduce a bug or a broken change.

    nylas (2.0.1)
      em-http-request
      rest-client (~> 1.6)
      yajl-ruby

Can you please version the gem dependencies?

E.g.

em-http-request (~> 1.1.2)
yajl-ruby (~> 1.2.1)

**Comment by pfista** [comment]
Fixed in b6cc78924d4d5dec349bf5760e3e0761e43e8464
