### ISSUE TITLE
Native Auth Method?

### ISSUE THREAD

**Issue by homerlex** [nylas/nylas-ruby#85]
Is there anything in the gem to POST a "native auth" request as described in https://nylas.com/cloud/docs?curl#native_authentication?  There is no sample Ruby code in the Native Authentication section of that doc.

Once I have the code I have the code I know I can use the token_for_code method to get the token.

**Comment by pfista** [comment]
Not currently, though an [example sinatra app](https://github.com/nylas/nylas-ruby/tree/master/examples/authentication) was just added that shows how to use the native auth apis directly
