### ISSUE TITLE
Allow multiple namespaces to be managed under one inbox token

### ISSUE THREAD

**Issue by nikhils777** [nylas/nylas-ruby#9]
The Inboxapp Docs provide this description for namespaces "Namespaces are essentially references to linked accounts. They are the top-level unit of a user’s data. For example, a user who has one Exchange account and two Gmail accounts linked to Inbox will have three distinct namespaces."
Right now, based on testing the rails console, viewing the sample inbox-ruby app, and reading through the inbox-app docs, it seems that there is no way to add new namespaces or access ones beyond the first one ( inbox.namespaces.first ) . How can this be done without having to maintain multiple inbox tokens for each user in order to link multiple email accounts to a webapp via inboxapp?

**Comment by singjsong** [comment]
Agreed with you on this. I suggested this to them in some back-and-forth emails. A competitor, context.io, implements an architecture that achieves this. Here's their Ruby gem if you/anyone else is interested: https://github.com/contextio/contextio-ruby I haven't dug too much into it myself, but it may be that it's more of a back-end architecture change to implement a global accessor to all resources rather than having a mere reflection of it in a Ruby gem.

**Comment by khamidou** [comment]
Hi @nikhils777,

We don't have yet a global accessor for all the namespaces --- the closest thing to it right now is our [accounts API](https://nilas.com/docs/knowledgebase#billing) which allows you to query the status of all the accounts linked to your app.

Right now, you'll have to store every token in the db and switch them when needed. We're working on this though. Can you tell me more about your use case?

**Comment by nikhils777** [comment]
I understand, so the key concern for AgentBright right now, as we are about to go live very soon is how will you manage billing for a single user who has 8 different email accounts linked to AgentBright via 8 Inboxapp tokens. We dont want to pay 8 times for one user ...

**Comment by nikhils777** [comment]
Sorry @khamidou I just read the billing part of the docs and it says you guys charge per email account connected. I got confused when i was reading namespaces and thought billing was per user ...

**Comment by khamidou** [comment]
Closing --- this is an upstream issue.
