### ISSUE TITLE
Public URL for the inline images in the email

### ISSUE THREAD

**Issue by abhijitsinha** [nylas/nylas-ruby#92]
We are integrating with nylas to allow our users to connect their mail accounts and show emails for those accounts and various other features. 

Currently we are facing one challenge which is to show inline images present in the email to our users? So wanted to know if there are public url for those inline images?

We can download the images and show them which we have already implemented but that will take some time before images are visible and users will see that lag so wanted to know if there is a provision for the public url like the download feature for the image - https://github.com/nylas/nylas-ruby/blob/master/lib/file.rb#L30

Grateful for any help you can provide. Thanks

**Comment by grinich** [comment]
We recommend using a server-side endpoint to proxy these files so you don't expose your access token anywhere. Most web frameworks allow you to create a streaming connection so your server doesn't need to download the entire file before returning it to the end user. Does that make sense? We don't have public URLs for any private mail data from the Nylas APIs.

**Comment by abhijitsinha** [comment]
Thanks @grinich for the reply. I understand what you mean but it will lead to bad user experience where images are shown to user with a delay. At least an authenticated url for the images will be added soon?

**Comment by khamidou** [comment]
Hi @abhijitsinha – for security reasons, we're not going to expose customer data without authentication. I strongly recommend that you serve these images from your server, and protect their access with authentication.
