### ISSUE TITLE
Files not present for a message

### ISSUE THREAD

**Issue by abhijitsinha** [nylas/nylas-ruby#95]
We have a Real Estate CRM application where we are integrating Nylas to enable our users to see their email exchanges between our user and their contacts. It works well - but there is one major issue.

For some of the messages - we are not able to see the files. This only happens for messages which are sent from our application using Sendgrid our email server. Can you tell us what could be the reason for this? Thank you.

**Comment by zspencer** [comment]
@abhijitsinha - Thanks for bringing this to our attention! I've notified @pfista and @khamidou , as this may be a known issue with the API that has been resolved.

**Comment by khamidou** [comment]
Hey @abhijitsinha – I'm going to close this issue as it's not related to the Ruby SDK itself. If you're still affected by it, please send an email to support@nylas.com. Thanks!
