### ISSUE TITLE
Please support tracking field in sending drafts

### ISSUE THREAD

**Issue by ekondr** [nylas/nylas-ruby#96]
For now the gem doesn't support tracking:
```
"tracking": {
  "links": true,
  "opens": true,
  "thread_replies": false,           
  "payload": "Any string you want!!"
}
```

When I set a tracking field for sending a draft the field is not sent.

**Comment by bhattjay** [comment]
Any update so far on this?

**Comment by pfista** [comment]
This has been addressed in the latest release. Thanks for your patience!
