### ISSUE TITLE
Nylas::InvalidRequest Exception: reply_to field can have at most one item

### ISSUE THREAD

**Issue by abhijitsinha** [nylas/nylas-ruby#98]
Hello Team,

Just wanted to check if this issue resolved - whenever I send more than email in reply to section it throws this error - *** Nylas::InvalidRequest Exception: reply_to field can have at most one item

I checked with Mike and Gleb from Nylas API - they say nylas do support this - can you please let me know if this is an issue in the gem?

Thanks

**Comment by abhijitsinha** [comment]
Checking if you guys got a chance to check this issue - thank you.

**Comment by zspencer** [comment]
@abhijitsinha - Thanks for bringing this to our attention! After looking into it briefly, I was able to execute the following code using the latest version of the gem and ruby 2.4
```
nylas = Nylas::API.new(...)
nylas.drafts.build({subject: "test reply-to!", to: [{ name: "recipient", email: "recipient@example.com" }], reply_to: [{name: "person", email: 'person@example.com' },{ name: "person 2", email: 'other-person@example.com' }], body: "Oh noooo"})
```

Please re-open if you notice this again.
